apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-frontend
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/stevo9061/sfr-k8s-configs.git
    targetRevision: HEAD
    path: dev/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: sfr-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true