apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sfr-app
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: stefanbi/backend:1867f13930a681d5c3fd03eaf27cad3c567bee0b
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: sfr
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          value: rootpassword
        - name: KAFKA_HOST
          value: kafka
        ports:
        - containerPort: 3000
