apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sfr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: stefanbi/backend:719409768db5075684455ca2bd234520bc0c83eb
        env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: sfr
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          value: rootpassword
        - name: KAFKA_HOST
          value: kafka
        ports:
        - containerPort: 3000
