apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: stefanbi/data:68de1c61ab4a5f35cff39a42d946d857a0d50f02
        env:
        - name: KAFKA_HOST
          value: kafka-service
        ports:
        - containerPort: 3001
