apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: stefanbi/data:d7d02c72e569ae103f41e55c8cb92630fc8bf049
        env:
        - name: KAFKA_HOST
          value: kafka-service
        ports:
        - containerPort: 3001
