apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: stefanbi/data:9affa2d61f27f260b41bcfbf107c7eb49ab4292e
        env:
        - name: KAFKA_HOST
          value: kafka-service
        ports:
        - containerPort: 3001
