apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: stefanbi/data:a5f2be11cd8aa7a48641b0e4677b91e2e8cd0ff5
        env:
        - name: KAFKA_HOST
          value: kafka-service
        ports:
        - containerPort: 3001
