apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: stefanbi/data:21ecc4a1902967ced3316a8dc70c79e2fe9884e4
        env:
        - name: KAFKA_HOST
          value: kafka-service
        ports:
        - containerPort: 3001
