apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: stefanbi/data:1867f13930a681d5c3fd03eaf27cad3c567bee0b
        env:
        - name: KAFKA_HOST
          value: kafka
        ports:
        - containerPort: 3001
