apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: stefanbi/data:d75415e72117ed331626697543473e39625d885b
        env:
        - name: KAFKA_HOST
          value: kafka-service
        ports:
        - containerPort: 3001
