apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: stefanbi/frontend:7d49de5b001ad32e46d3ebb00b06309154e22964
        ports:
        - containerPort: 4200
